name: PlayerBounties-OG
version: '${version}'
main: com.tcoded.playerbountiesplus.PlayerBountiesOG
api-version: '${apiVersion}'
authors: [ TechnicallyCoded, NotAlexNoyle ]
description:  A player bounty plugin for TrueOG Network using our custom Diamond Economy.
website: https://github.com/true-og/PlayerBounties-OG/
folia-supported: false

depend:
  - DiamondBank-OG
  - CoreProtect-OG
softdepend:
  - SimpleClans
  - Unions-OG
  - LuckPerms

commands:
  bounty:
    permission: playerbountiesog.command.bounty
    aliases: [bounties, prime, primes]
  playerbountiesplusadmin:
    permission: playerbountiesog.command.admin
    aliases: [playerbountiesplus, pbpa, pbp]

permissions:
  playerbountiesog.command.bounty:
    default: true
  playerbountiesog.command.admin:
    default: op
    children:
      playerbountiesog.command.admin.version: {}
      playerbountiesog.command.admin.reload: {}
      playerbountiesog.command.admin.bounty.set: {}
      playerbountiesog.command.admin.bounty.add: {}
      playerbountiesog.command.admin.bounty.remove: {}
      playerbountiesog.command.admin.bounty.delete: {}
      playerbountiesog.command.admin.bounty.get: {}
  playerbountiesog.command.bounty.set:
    default: true
  playerbountiesog.command.bounty.add:
    default: true
  playerbountiesog.event.claim:
    default: true
