name: PlayerBounties-OG
version: '${version}'
main: com.tcoded.playerbountiesplus.PlayerBountiesPlus
api-version: '${apiVersion}'
authors: [ TechnicallyCoded, NotAlexNoyle ]
description:  A player bounty plugin for TrueOG Network using our custom Diamond Economy.
website: https://github.com/true-og/PlayerBounties-OG/
folia-supported: false

depend:
  - Vault
softdepend:
  - ClansLite
  - ClansPlus
  - Parties
  - BetterTeams
  - SimpleClans
  - Towny

commands:
  bounty:
    permission: playerbountiesplus.command.bounty
    aliases: [bounties, prime, primes]
  playerbountiesplusadmin:
    permission: playerbountiesplus.command.admin
    aliases: [playerbountiesplus, pbpa, pbp]

permissions:
  playerbountiesplus.command.bounty:
    default: true
  playerbountiesplus.command.admin:
    default: op
    children:
      playerbountiesplus.command.admin.version: {}
      playerbountiesplus.command.admin.reload: {}
      playerbountiesplus.command.admin.bounty.set: {}
      playerbountiesplus.command.admin.bounty.add: {}
      playerbountiesplus.command.admin.bounty.remove: {}
      playerbountiesplus.command.admin.bounty.delete: {}
  playerbountiesplus.command.bounty.set:
    default: true
  playerbountiesplus.event.claim:
    default: true
